DISCORD_PREVIEW_BOT_TOKEN={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/DISCORD_PREVIEW_BOT_TOKEN }}
DISCORD_GUILD_ID={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/DISCORD_GUILD_ID }}
DISCORD_E2E_ANNOUNCEMENT_CHANNEL_ID={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/j7kkoyn3d4oth4yciqni7qyhui }}
DISCORD_E2E_RECEIVER_CHANNEL_ID={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/5dfywo6mrp2mfags4dxmsj4ale }}
EMAIL_TO={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/EMAIL_TO }}
RESEND_PREVIEW_API_KEY={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/2dz4hpmhrtykmb3yaawfh5gemu }}
EMAIL_FROM_NAME={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/EMAIL_FROM_NAME }}
EMAIL_FROM_EMAIL={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/EMAIL_FROM_EMAIL }}
ADMIN_PREVIEW_TOKEN={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/ADMIN_PREVIEW_TOKEN }}
CF_ACCESS_CLIENT_ID={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/CF_ACCESS_CLIENT_ID }}
CF_ACCESS_CLIENT_SECRET={{ op://github-actions/jzwlhhnq7fhnsoazz2esnl4xt4/add more/CF_ACCESS_CLIENT_SECRET }}
